In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('/content/50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000
np.random.seed(9)
df = df.sample(5)
df


R&D Spend  Administration  Marketing Spend     Profit
21   7.838947       15.377343        29.973729  11.131302
37   4.406995        5.128314        19.702942   8.994914
2   15.344151       10.114555        40.793454  19.105039
14  11.994324       15.654742        25.651292  13.260265
44   2.217774       15.480614         2.833472   6.520033

In [5]:
df.iloc[:,0:-1]


R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37   4.406995        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       15.654742        25.651292
44   2.217774       15.480614         2.833472

In [7]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [8]:
df.head()

R&D Spend  Administration  Marketing Spend     Profit
21   7.838947       15.377343        29.973729  11.131302
37        NaN        5.128314        19.702942   8.994914
2   15.344151       10.114555        40.793454  19.105039
14  11.994324             NaN        25.651292  13.260265
44   2.217774       15.480614         2.833472        NaN

In [9]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [10]:
# 0th Iteration
df0

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37   9.348799        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.525207        25.651292
44   2.217774       15.480614         2.833472

In [12]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37        NaN        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.525207        25.651292
44   2.217774       15.480614         2.833472

In [13]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

Administration  Marketing Spend
21       15.377343        29.973729
2        10.114555        40.793454
14       11.525207        25.651292
44       15.480614         2.833472

In [14]:
y = df1.iloc[[0,2,3,4],0]
y

21     7.838947
2     15.344151
14    11.994324
44     2.217774
Name: R&D Spend, dtype: float64

In [15]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([17.62699479])

In [16]:
df1.iloc[1,0] = 23.14

In [17]:
df1

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.525207        25.651292
44   2.217774       15.480614         2.833472

In [19]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324             NaN        25.651292
44   2.217774       15.480614         2.833472

In [20]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

R&D Spend  Marketing Spend
21   7.838947        29.973729
37  23.140000        19.702942
2   15.344151        40.793454
44   2.217774         2.833472

In [21]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.377343
37     5.128314
2     10.114555
44    15.480614
Name: Administration, dtype: float64

In [22]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.7662703])

In [24]:
df1.iloc[3,1] = 11.06
df1

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614         2.833472

In [26]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614              NaN

In [27]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

R&D Spend  Administration
21   7.838947       15.377343
37  23.140000        5.128314
2   15.344151       10.114555
14  11.994324       11.060000

In [28]:
y = df1.iloc[0:4,-1]
y

21    29.973729
37    19.702942
2     40.793454
14    25.651292
Name: Marketing Spend, dtype: float64

In [29]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([27.33065522])

In [30]:
df1.iloc[4,-1] = 31.56

In [31]:
# After 1st Iteration
df1

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.140000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614        31.560000

In [32]:
# Subtract 0th iteration from 1st iteration

df1 - df0

R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37  13.791201        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000       -0.465207         0.000000
44   0.000000        0.000000        28.726528

In [34]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37        NaN        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.060000        25.651292
44   2.217774       15.480614        31.560000

In [35]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([22.47450087])

In [36]:
df2.iloc[1,0] = 23.78

In [38]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.54821944])

In [39]:
df2.iloc[3,1] = 11.22

In [40]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([32.01261897])

In [41]:
df2.iloc[4,-1] = 31.56
df2

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  23.780000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.220000        25.651292
44   2.217774       15.480614        31.560000

In [42]:
df2-df1

R&D Spend  Administration  Marketing Spend
21       0.00            0.00              0.0
37       0.64            0.00              0.0
2        0.00            0.00              0.0
14       0.00            0.16              0.0
44       0.00            0.00              0.0

In [44]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37        NaN        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.220000        25.651292
44   2.217774       15.480614        31.560000

In [45]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.16034641])

In [46]:
df3.iloc[1,0] = 24.57

In [48]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.70996317])

In [49]:
df3.iloc[3,1] = 11.37

In [50]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([37.19632922])

In [51]:
df3.iloc[4,-1] = 45.53
df2.iloc[3,1] = 11.22
df3

R&D Spend  Administration  Marketing Spend
21   7.838947       15.377343        29.973729
37  24.570000        5.128314        19.702942
2   15.344151       10.114555        40.793454
14  11.994324       11.370000        25.651292
44   2.217774       15.480614        45.530000

In [52]:
df3-df2

R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.79            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.15             0.00
44       0.00            0.00            13.97