In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [6]:
x,y = load_diabetes(return_X_y = True)

In [9]:
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [10]:
x.shape

(442, 10)

In [11]:
y.shape

(442,)

# **using Sklearn's Linear Regression**

In [12]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=2)

In [15]:
print(x_train.shape)
print(x_test.shape)

(353, 10)
(89, 10)


In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
reg = LinearRegression()

In [18]:
reg.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred = reg.predict(x_test)

In [20]:
from sklearn.metrics import r2_score

In [21]:
r2_score(y_test,y_pred)

0.4399338661568968

In [22]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [23]:
reg.intercept_

np.float64(151.88331005254167)

# **Making our own linear regression class**

In [35]:
class MyLr:

  def __init__(self):
      self.coef_ = None
      self.intercept_ = None

  def fit(self, x_train,y_train):
      x_train = np.insert(x_train,0,1,axis=1)

      #calculate the coefficient
      betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
      self.intercept_ = betas[0]
      self.coef_ = betas[1:]

  def predict(self, x_test):
      y_pred = np.dot(x_test,self.coef_) + self.intercept_
      return y_pred

In [36]:
lr = MyLr()

In [37]:
lr.fit(x_train,y_train)

In [38]:
x_train.shape

(353, 10)

In [40]:
y_pred = lr.predict(x_test)

In [41]:
r2_score(y_test,y_pred)

0.43993386615689634

In [42]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [43]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [44]:
lr.intercept_

np.float64(151.88331005254165)